### ISSUE TITLE
Wandsbek salamae isolate

### ISSUE THREAD

**Issue by andersgs** [phac-nml/sistr_cmd#28]
Hi.

I have a sample that is subspecies salamae and Serotype Wandsbek. The H1 antigen for this serotype should be `z10` but sistr is predicting `b`. 

I have dug through the BLAST results and the code. I noticed that in `H1Prediction` (line 225) you first filter the results by the number of mismatches (maximum of 25) and minimum length of alignment (min 700). With these settings, it seems you are ok with at most ~96.4% identity (25/700), but it says nothing about the coverage of the gene.

I pulled out the BLAST matches for `z10` and `b` on the `fliC` locus as outputted by `sistr` (using `-MM` option) and parsed them into an `R` `data.frame` ([wandsbek_blast_fliC_res.txt](https://github.com/peterk87/sistr_cmd/files/2574082/wandsbek_blast_fliC_res.txt)). 

If we look at the distribution of coverage this is what we get:

![image](https://user-images.githubusercontent.com/3836603/48381450-b15ad800-e690-11e8-97a0-f26a4b2d047b.png)

If we look at the distribution of `mismatches` vs `length` we get the following:

![image](https://user-images.githubusercontent.com/3836603/48381494-f41cb000-e690-11e8-9476-04c8c0e92eef.png)

If we look at the distribution of `coverage` vs `percent identity` we get the following:

![image](https://user-images.githubusercontent.com/3836603/48381714-1fec6580-e692-11e8-85bb-5a311e21a9a6.png)

Indeed, if I filter by the criteria currently in the code, the best match is a `b` but its blast alignment covers less than 50% of the locus. On the other hand, the `z10` locus has 100% coverage and >98% identity. 

Obviously, I am not clear on the process that led to the choice of these thresholds. But, these thresholds do not take in to account that BLAST is a local aligner. Perhaps filtering by coverage (`length/qlen`) and then `percent identity` would be a better approach than absolute length and absolute number of mismatches.

Best. Anders.

**Comment by jrober84** [comment]
As of v. 1.1.0 sistr uses bitscore sorting of blast results to determine the top hit. Wandsbek is identified as II 21:z10:[z6] using SRR3048916 and SRR2911744 since the WKLM lists it as a synonym of II 21:z10:z6. If you have more representatives of these types and would like to add them to the sistr db please let me know.  We are unable to detect the serogroup marker for this serotype as it is missing the wzx gene present in other O:21 serotypes like Minnesota. This could be due to the library preparation since it has been documented that the GC content in this region can pose a problem for Illumina preps. https://aem.asm.org/content/86/5/e02265-19.abstract
