### ISSUE TITLE
"sistr" running time benchmark

### ISSUE THREAD

**Issue by npavlovikj** [phac-nml/sistr_cmd#41]
Hi,

I am using `sistr` on ~20,000 Salmonella genomes with 4 threads. `sistr` has been running for almost 18 days. I was wondering if there is any way or setting I can use to improve the running time and whether you have some benchmarking of how long it will actually take to finish these analysis.

The command I am using is `sistr -t 4 --qc -vv --alleles-output allele_results.json --novel-alleles novel_alleles.fasta --cgmlst-profiles cgmlst_profiles.csv -f csv -o sistr_output.csv *.fasta`

Thank you,
Natasha

**Comment by jrober84** [comment]
Hello,

depending on your particular analysis goals, there are already in sillico predictions for most publicly available genomes on enterobase which has SISTR serotyping results on public records. Testing with 4 threads shows ~20secs per genome with your selected parameters in our HPC compute environment. This would mean ~ 4.6 days of compute time for 20,000 genomes. If you have that many genomes to process it would be faster to split them up into smaller jobs and take advantage of extra compute resources your have. Since sistr would be processing your list of genomes sequentially.

-Jams

**Comment by npavlovikj** [comment]
Many thanks for the prompt reply @jrober84 !
I wasn't aware that I can run "sistr" per genome and then concatenate the results, so I think that is what I will try next.

Thank you,
Natasha
